### PR TITLE
Add support for building with Gradle

### PR DESCRIPTION
**Pull request by cketti**
It seems to build fine. But I haven't actually tested the result.
At the very least it should give you a good starting point.

### CODE REVIEW

**Comment by eighthave** [comment]
thanks, that was fast!  Any particular reason why you embedded gradle v1.8 libs rather than v2.2.1?

**Comment by cketti** [comment]
I copied the stuff over from another project. It's possible that the Gradle wrapper script is not the most recent version. But the Gradle version that is downloaded by the wrapper is 2.2.1.

See https://github.com/guardianproject/IOCipher/pull/6/files#diff-fd9d61e37d939c941e7a62077f38d62dR6

**Comment by eighthave** [comment]
I tried included v2.2.1's gradle-wrapper.jar and `./gradlew` gave me a stacktrace, so it seems like `./gradlew` requires v1.8's jar.  But really, it seems that `gradle/wrapper/gradle-wrapper.jar` is some mystery binary that is generated somehow by gradle, it doesn't match the `gradle-wrapper.jar` that is shipped with the official releases.  So I'm going to skip adding the mystery binaries to this repo for now.  With all the work towards reproducible builds going on, `./gradlew` seems like huge step backwards.

**Comment by OnlyInAmerica** [comment]
`./gradlew` allows you to work on projects requiring different versions of gradle without the hassle of maintaining multiple installations on your development machine. It also assures that all developers of the repository use the same version of gradle. It's definitely a good step towards reproducible builds.

Instead of copying the wrapper files (the .jar and ./gradlew binary) you can generate them with gradle itself:

Add the following to your root build.gradle file:

```groovy
task wrapper(type: Wrapper) {
    gradleVersion = '2.2.1' 
}
```

Then invoke `gradle wrapper` from your root project directory to generate all the wrapper files. From there on out you should always run gradle commands on your project via `./gradlew`. (When you create projects in Android Studio the initial wrapper generation is handled automatically)

**Comment by eighthave** [comment]
@OnlyInAmerica I didn't see anyway to verify the generated files were indeed from the official releases, and the build system is master of all that happens to the result.  Flipping a single bit in a binary can introduce a vulnerability.  So just committing some generated files because the script made them is contrary to the work we're doing on reproducible builds.

For more info, here's one good source:
https://www.youtube.com/watch?v=5pAen7beYNc

**Comment by eighthave** [comment]
I should add, I tried taking apart the build process of the gradlew wrapper stuff, and it definitely was not obvious what is happening there.  I think it is easy enough to use jars, and you can already reproduce the official IOCipher releases using the `./make-release-build` and `./compare-to-official-release` scripts included in the git repo.

**Pull request closed without merging**
