### PR TITLE
update build files to work with latest gradle and Java

### PR DESCRIPTION
**Pull request by n8fr8**
thoughts? This is the only way I could get it to build on my machine

### CODE REVIEW

**Comment by eighthave** [comment]
I see no reason to upgrade this stuff, since the build works fine with the standard tools: `./gradlew assemble`:  https://gitlab.com/guardianproject/iocipher/-/jobs/246279055  I think changing the build tools can only cause issues in the build.  The binaries produced here work in any app, as far as I've seen.

You can always keep commits like this locally, I often do this kind of thing, and just name the commit "DO NOT MERGE".

**Comment by n8fr8** [comment]
Okey doke!

**Comment by abeluck** [comment]
@eighthave what version of java are you running though?

If there are java version incompats, then I think updating this stuff to fix that is a good thing.

**Comment by eighthave** [comment]
It is true, you need quite new gradle versions to work with JDK newer
than 8.  If you use the Java JDK that comes with Android Studio, then it
works, that's stuck on version 8.  I don't think you have to change the
gradle android plugin version though.  Each new version of gradle
android plugin has new and different bugs in reproducible builds.  Fun
stuff :'-(

**Pull request closed without merging**
